services:
  app:
    build: .
    ports:
      - "3000:3000"
    container_name: zadanie-cheil
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
    restart: unless-stopped